services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend.Dockerfile
    ports:
      - "5173:80"

  backend:
    build:
      context: .
      dockerfile: .docker/backend.Dockerfile
    ports:
      - "8000:8000"
